// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web configuration
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_0m23CnSMDUEpj4VxxGQSyJRX8__WgE',
    appId: '1:801082618247:android:bc50993e40bbc11b932322',
    messagingSenderId: '801082618247',
    projectId: 'flutter-signup-app-d7d78',
    storageBucket: 'flutter-signup-app-d7d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-0vC0x8sw8DBUoCuiGiLJZ2deK_IQ1Q',
    appId: '1:523980747506:ios:160f9d084cab3ac15f166b',
    messagingSenderId: '523980747506',
    projectId: 'flutter-chat-app-42c5e',
    storageBucket: 'flutter-chat-app-42c5e.appspot.com',
    iosClientId:
        '523980747506-1fd8e8pg1ld5dvnn854b2pvnt6vjm9vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxeksxf_fnioC4TFa4WG622Zn8X9turYI',
    appId: '1:801082618247:web:b977f9e142755831932322',
    messagingSenderId: '801082618247',
    projectId: 'flutter-signup-app-d7d78',
    authDomain: 'flutter-signup-app-d7d78.firebaseapp.com',
    storageBucket: 'flutter-signup-app-d7d78.appspot.com',
    measurementId: 'G-QQ62KMCFBS',
  );

  // Add web configuration
}
